changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bugfix"
        - "bug"
    - title: "📚 Docs"
      label: "documentation"
    - title: "🌐 I18N"
      label: "i18n"
    - title: "🧰 Maintenance"
      label: "i18n"
