apiVersion: v1
kind: Service
metadata:
  name: scan-deduplicator-validator
  namespace: scan-deduplicator
  labels:
    app: scan-deduplicator-validator
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: scan-deduplicator-validator
