on: [push, pull_request]
name: "Tests"
permissions:
  contents: read
env:
  GO_STATIC_CHECK_VERSION: "2024.1.1"
jobs:
  scan-deduplicator:
    name: "Scan Deduplicator"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      - name: "Lint"
        run: go vet ./...
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "${{ env.GO_STATIC_CHECK_VERSION }}"
      - name: "Test"
        run: go test -cover ./...
